ARG KAR_BASE=us.icr.io/research/kar-dev/kar
ARG SDK_BASE=us.icr.io/research/kar-dev/sdk-nodejs-v12

FROM $KAR_BASE as kar

FROM $SDK_BASE

# Copy in kar executable to enable "local mode" style when running under Knative
RUN mkdir -p /kar/bin
COPY --from=kar /kar/kar /kar/bin/kar
COPY docker/kar-wrapper.sh /kar/bin/kar-wrapper.sh

# Next copy package*.json and run npm install --prod on all tests

# Example: actors-ykt
WORKDIR /kar/examples/actors-ykt
COPY actors-ykt/*.json ./
RUN npm install --prod

# Example: helloWorld
WORKDIR /kar/examples/helloWorld
COPY helloWorld/*.json ./
RUN npm install --prod

# Example: unit-tests
WORKDIR /kar/examples/unit-tests
COPY unit-tests/*.json ./
RUN npm install --prod

# Example: stockPriceEvents
WORKDIR /kar/examples/stockPriceEvents
COPY stockPriceEvents/*.json ./
RUN npm install --prod

# copy JavasScript code

# Example: actors-ykt
WORKDIR /kar/examples/actors-ykt
COPY actors-ykt/*.js ./

# Example: helloWorld
WORKDIR /kar/examples/helloWorld
COPY helloWorld/*.js ./

# Example: unit-tests
WORKDIR /kar/examples/unit-tests
COPY unit-tests/*.js ./

# Example: stockPriceEvents
WORKDIR /kar/examples/stockPriceEvents
COPY stockPriceEvents/*.js ./

WORKDIR /kar/examples

CMD /kar/bin/kar-wrapper.sh
