ARG SDK_BASE=us.icr.io/research/kar-dev/sdk-nodejs-v12

FROM $SDK_BASE

# Example: express
WORKDIR /kar/examples/express
COPY express/*.js express/*.json ./
RUN npm install --prod

# Example: actors-ykt
WORKDIR /kar/examples/actors-ykt
COPY actors-ykt/*.js actors-ykt/*.json ./
RUN npm install --prod

# Example: helloWorld
WORKDIR /kar/examples/helloWorld
COPY helloWorld/*.js helloWorld/*.json ./
RUN npm install --prod

# Example: unit-tests
WORKDIR /kar/examples/unit-tests
COPY unit-tests/*.js unit-tests/*.json ./
RUN npm install --prod

WORKDIR /kar/examples

CMD node "$MAIN"
