ARG KAR_BASE=us.icr.io/research/kar-dev/kar

FROM $KAR_BASE as kar

FROM openliberty/open-liberty:20.0.0.9-kernel-java11-openj9-ubi

USER default

# Copy in kar cli to enable local mode for IBM Code Engine
COPY --from=kar /kar/bin/kar /kar/bin/kar

# Inject wrapper script that detects local vs. sidecar mode
COPY runner /kar/bin/runner
CMD /kar/bin/runner
