apiVersion: apps/v1
kind: Deployment
metadata:
  name: ykt-server
  labels:
    name: ykt-server
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: ykt-server
  template:
    metadata:
      labels:
        name: ykt-server
      annotations:
{{ if not .Values.noSidecar }}
        kar.ibm.com/app: ykt
        kar.ibm.com/actors: Company,Site,Office,Researcher
        kar.ibm.com/verbose: {{ .Values.verbose }}
{{ end }}
    spec:
{{ if .Values.noSidecar }}
      volumes:
      - name: kar-ibm-com-config
        secret:
          secretName: kar.ibm.com.runtime-config
{{ end }}
      containers:
      - name: server
        image: {{ .Values.image }}

        env:
{{ if .Values.noSidecar }}
        - name: KAR_SIDECAR_IN_CONTAINER
          value: "true"
        - name: KAR_APP
          value: ykt
        - name: KAR_EXTRA_ARGS
          value: -config_dir /var/run/secrets/kar.ibm.com -v {{ .Values.verbose }} -actors Company,Site,Office,Researcher
        volumeMounts:
        - mountPath: /var/run/secrets/kar.ibm.com
          name: kar-ibm-com-config
          readOnly: true
{{ end }}
