#
# Copyright IBM Corporation 2020,2022
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARG PYTHON_RUNTIME=localhost:5000/kar/kar-sdk-python-3.8

FROM $PYTHON_RUNTIME

RUN mkdir /python_kar/python-unit-tests
WORKDIR /python_kar/python-unit-tests

COPY pytest.ini pytest.ini

COPY service_server.py service_server.py
COPY test_service_methods.py test_service_methods.py

COPY actor_server.py actor_server.py
COPY test_actor_server.py test_actor_server.py

COPY actor_state_server.py actor_state_server.py
COPY test_state_management.py test_state_management.py

COPY actor_state_submap_server.py actor_state_submap_server.py
COPY test_state_submap_management.py test_state_submap_management.py

COPY actor_events_server.py actor_events_server.py
COPY test_actor_events_server.py test_actor_events_server.py

COPY launch.sh launch.sh
COPY container-env.sh container-env.sh

ENV PATH=/python_kar/bin:$PATH

CMD source container-env.sh && sh launch.sh
