apiVersion: apps/v1
kind: Deployment
metadata:
  name: kar-injector
  labels:
    app: kar-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kar-injector
  template:
    metadata:
      labels:
        app: kar-injector
    spec:
      containers:
      - name: injector
        image: us.icr.io/groved/kar-injector:latest
        imagePullPolicy: Always
        command: ["/kar/kar-injector", "--tls-cert-file", "/var/run/secrets/tls/tls.crt", "--tls-private-key-file", "/var/run/secrets/tls/tls.key", "--port", "8443"]
        ports:
        - containerPort: 8443
          name: webhook-api
        volumeMounts:
        - name: tls-certs
          mountPath: /var/run/secrets/tls
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: kar-injector-tls
---
apiVersion: v1
kind: Service
metadata:
  name: kar-injector
spec:
  selector:
    app: kar-injector
  ports:
    - port: 443
      targetPort: webhook-api
# ---
# apiVersion: admissionregistration.k8s.io/v1beta1
# kind: MutatingWebhookConfiguration
# metadata:
#   name: demo-webhook
# webhooks:
#   - name: kar-injector.webhook-demo.svc
#     clientConfig:
#       service:
#         name: kar-injector
#         namespace: webhook-demo
#         path: "/mutate"
#       caBundle: ${CA_PEM_B64}
#     rules:
#       - operations: [ "CREATE" ]
#         apiGroups: [""]
#         apiVersions: ["v1"]
#         resources: ["pods"]
