apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kar-sidecar-injector-webhook
webhooks:
  - name: kar-injector.kar.svc
    clientConfig:
      service:
        name: kar-injector
        namespace: kar
        path: "/inject-sidecar"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVBQ0NRRE5pMXljNFJKdnRUQU5CZ2txaGtpRzl3MEJBUXNGQURBK01Rc3dDUVlEVlFRR0V3SlYKVXpFTE1Ba0dBMVVFQ0F3Q1Rsa3hFVEFQQmdOVkJBY01DRmx2Y210MGIzZHVNUTh3RFFZRFZRUUtEQVpMUVZJZwpRMEV3SGhjTk1qQXdNakk0TWpBek16RTJXaGNOTWpBd016STVNakF6TXpFMldqQStNUXN3Q1FZRFZRUUdFd0pWClV6RUxNQWtHQTFVRUNBd0NUbGt4RVRBUEJnTlZCQWNNQ0ZsdmNtdDBiM2R1TVE4d0RRWURWUVFLREFaTFFWSWcKUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURNc0IvYjhYREgrTjhYNlVTdAp0UkdtNWxkemovWWxsWWxuWG1FaXZUU2liMjM5c1ZCOUNGVDFYZmNTSFJnR2E4YXd1czBTbGprV0RERXJwWlY1CkVudVc3Sy9pZGE1TE0zZ2xtbFJUTnRKalo5RUdLRDdQZHRkWXlZQ2l2cFNBMHJaTklPcVV0SFBiZ2MzWWl1RTcKeGxwNHVOL2U1QXhYSW9tNTJlMGtFWTc0ZkdrU1RJeXFIQ3ZPcldVUHN6ZE1sQnNGRHViMVJ4YWQrbG1tMEg4SApWbFFlTUlXRHIyNVJrcUxFK3hCbkgybFdKaUVPVTFuU2hlRU1UdkNxZCtSbVo5OWhjRVQ1ZDNneG9ySWoxb0QxCmM2MldHRXl2SzNmTE1HNkEyVlRJZDM3L3NKeURFUkVkYmd2RXpMa2xEWTlKd3RSUEhkbGQzQVIvb2F2THBKOWsKNGl5eEFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUpDNFR4bzFEcWV3YUpBVmNwREJUYU8vYlJqcQowMmxvZWlPSUZwZy9WeHNrenc3SEpsbklydW44dStnQzRrYTAvMFFRWnBNRHlXTEQ2R3c1QnliZjdHMHJwVVh2CkkreTRoTFlPb0JlMkVkdVd6bnNjNCtOd0pWNnlER1R1Um5ZNm9ncXBoM0ZpODNzWGlzTXoreHZ2NTdQUVFwV2UKSnQxZU94dVkwUWpSdDA2dmhpLzF2dGZWdnZuRjhFS2RxS0FCSWRPN0RiOXRqUHFtUWU1VVk5SjlDSVRBRlZEdgphUGEwdHBueXUwWGtBa1lMSTQvczY4T1ZSZVBoRHZWd0dVOE1SazlxK1ZMK3c1S3NqSjdFRDNLTFhVMWJudlY5ClRXVlh5VDBwdDY3M01ZblJWMndpbGFVSGcyMHE3VU1RTGhpcmpNanB6YUlGaGQvc3hBNFI4aGgwVzRNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
