language: go
services:
  - docker

go:
  - 1.15.x

before_install:
  - ./ci/setup.sh

jobs:
  include:
    - stage: test
      name: local
      script:
        - ./scripts/docker-compose-start.sh || travis_terminate 1
        - make cli || travis_terminate 1
        - ./ci/testLocal.sh
        - ./ci/testJavaLocal.sh
    - name: in-cluster
      script:
        -  ./scripts/kind-start.sh || travis_terminate 1
        - make cli || travis_terminate 1
        - make docker || travis_terminate 1
        - ./scripts/kar-k8s-deploy.sh || travis_terminate 1
        - ./ci/testInCluster.sh
    - stage: deploy
      script: ./ci/pushImages.sh
      if: NOT type in (pull_request) AND repo = IBM/kar AND (branch = main OR tag =~ ^v)
