language: go
services:
  - docker
sudo: required

go:
  - 1.15.x

before_install:
  - ./travis/setup.sh

jobs:
  include:
    - stage: test
      name: local
      script:
        - ./scripts/docker-compose-start.sh || travis_terminate 1
        - make cli || travis_terminate 1
        - make installJavaSDK || travis_terminate 1
        - ./travis/testLocal.sh
        - ./travis/testJavaLocal.sh
    - name: in-cluster
      script:
        -  ./scripts/kind-start.sh || travis_terminate 1
        - make cli || travis_terminate 1
        - make docker || travis_terminate 1
        - ./scripts/kar-k8s-deploy.sh || travis_terminate 1
        - ./travis/testInCluster.sh
