#
# Copyright IBM Corporation 2020,2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

language: go
services:
  - docker

go:
  - 1.15.x

before_install:
  - ./ci/setup.sh

jobs:
  include:
    - stage: test
      name: local
      script:
        - ./scripts/docker-compose-start.sh || travis_terminate 1
        - make cli || travis_terminate 1
        - make installJavaSDK || travis_terminate 1
        - ./ci/testLocal.sh
        - ./ci/testJavaLocal.sh
    - name: local-rpclib
      env:
      script:
        - ./scripts/docker-compose-start.sh || travis_terminate 1
        - make cli || travis_terminate 1
        - make installJavaSDK || travis_terminate 1
        - KAR_EXTRA_ARGS=-rpclib ./ci/testLocal.sh
        # Disabled until rpclib implements continuations
        # - KAR_EXTRA_ARGS=-rpclib ./ci/testJavaLocal.sh
    - name: in-cluster
      script:
        - ./scripts/kind-start.sh || travis_terminate 1
        - make cli || travis_terminate 1
        - make docker || travis_terminate 1
        - ./scripts/kar-k8s-deploy.sh || travis_terminate 1
        - ./ci/testInCluster.sh
    - stage: deploy
      script: ./ci/pushImages.sh
      if: NOT type in (pull_request) AND repo = IBM/kar AND (branch = main OR tag =~ ^v)
