language: go
services:
  - docker

go:
  - 1.13

script:
  - ./travis/build.sh

deploy:
  - provider: script
    script: "./travis/pushImages.sh ${TRAVIS_TAG}"
    on:
      tags: true
      all_branches: true
      repo: solsa/kar
  - provider: script
    script: "./travis/pushImages.sh nightly"
    on:
      branch: master
      repo: solsa/kar
