language: go
services:
  - docker
sudo: required

go:
  - 1.13

before_install:
  - ./build/ci/setup.sh && ./build/ci/start-kind.sh

script:
  - ./build/ci/build.sh

deploy:
  - provider: script
    script: "./build/ci/pushImages.sh ${TRAVIS_BRANCH} ${TRAVIS_TAG}"
    on:
      tags: true
      all_branches: true
      repo: solsa/kar
  - provider: script
    script: "./build/ci/pushImages.sh master latest"
    on:
      branch: master
      repo: solsa/kar
