language: go
services:
  - docker
sudo: required

go:
  - 1.15.x

before_install:
  - ./travis/setup.sh && ./scripts/start-kind.sh

script:
  - (./travis/build.sh && ./travis/start-kar.sh) || travis_terminate 1
  - ./travis/createTestTopic.sh
  - ./examples/actors-ykt/createTopics.sh
  - ./travis/testLocal.sh
  - ./travis/testJavaLocal.sh
  - ./travis/testInCluster.sh

deploy:
  - provider: script
    script: "./travis/pushImages.sh ${TRAVIS_BRANCH} ${TRAVIS_TAG}"
    on:
      tags: true
      all_branches: true
      repo: solsa/kar
  - provider: script
    script: "./travis/pushImages.sh master latest"
    on:
      branch: master
      repo: solsa/kar
