apiVersion: v1
kind: Service
metadata:
  name: kar-kafka
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: kar-kafka
spec:
  type: ClusterIP
  clusterIP: None
  selector:
      {{- include "kar.selectorLabels" . | nindent 6 }}
      name: kar-kafka
  ports:
  - name: kafka
    port: {{ .Values.kafka.port }}
    targetPort: {{ .Values.kafka.port }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kar-kafka
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: kar-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kar.selectorLabels" . | nindent 6 }}
      name: kar-kafka
  serviceName: kar-kafka
  template:
    metadata:
      labels:
        {{- include "kar.selectorLabels" . | nindent 8 }}
        name: kar-kafka
    spec:
      initContainers:
      - name: wait-for-zookeeper
        image: busybox
        command: ["sh", "-c", 'result=1; until [ $result -eq 0 ]; do OK=$(echo ruok | nc -w 1 {{ include "kar.zookeeper_host_zero" . }} {{ .Values.zk.port }}); if [ "$OK" == "imok" ]; then result=0; echo "zookeeper returned imok!"; else echo waiting for zookeeper to be ready; sleep 1; fi; done; echo "Success: zookeeper is up"']
      containers:
      - name: kafka
        image: {{ .Values.kafka.imageRegistry }}/{{ .Values.kafka.imageName }}:{{ .Values.kafka.imageTag }}
        ports:
        - name: kafka
          containerPort: {{ .Values.kafka.port }}
        env:
        - name: HOSTNAME_COMMAND
          value: hostname -f
        - name: KAFKA_ADVERTISED_PORT
          value: {{ .Values.kafka.port | quote }}
        - name: KAFKA_PORT
          value: {{ .Values.kafka.port | quote }}
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INCLUSTER:PLAINTEXT
        - name: KAFKA_LISTENERS
          value: INCLUSTER://:{{ .Values.kafka.port }}
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INCLUSTER://_{HOSTNAME_COMMAND}:{{ .Values.kafka.port }}
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INCLUSTER
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: {{ include "kar.zookeeper_host_zero" . }}:{{ .Values.zk.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kar-kafka-console
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: kar-kafka-console
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kar.selectorLabels" . | nindent 6 }}
      name: kar-kafka-console
  template:
    metadata:
      labels:
        {{- include "kar.selectorLabels" . | nindent 8 }}
        name: kar-kafka-console
    spec:
      containers:
      - name: console
        image: {{ .Values.kafka.imageRegistry }}/{{ .Values.kafka.imageName }}:{{ .Values.kafka.imageTag }}
        command:
        - "/bin/bash"
        - "-c"
        - "tail -f /dev/null"
        env:
        - name: KAFKA_BOOTSTRAP_SERVER
          value: {{ include "kar.kafka_host_zero" . }}:{{ .Values.kafka.port }}
        - name: KAFKA_BROKER
          value: {{ include "kar.kafka_host_zero" . }}:{{ .Values.kafka.port }}