apiVersion: v1
kind: Secret
metadata:
  name: kar.ibm.com.runtime-config
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: kar.ibm.com.runtime-config
data:
{{- if .Values.kafka.internal }}
  kafka_brokers: {{ print ( include "kar.kafka_host_zero" . ) ":" .Values.kafka.port | b64enc }}
  kafka_version: {{ .Values.kafka.version | b64enc }}
{{ else }}
  kafka_brokers: {{ .Values.kafka.externalConfig.brokers | b64enc }}
  kafka_password: {{ .Values.kafka.externalConfig.password | b64enc }}
  kafka_username: {{ .Values.kafka.externalConfig.username | b64enc }}
  kafka_version: {{ .Values.kafka.externalConfig.version | b64enc }}
{{ end -}}
{{- if .Values.redis.internal }}
  redis_host: {{ include "kar.redis_host" . | b64enc }}
  redis_port: {{ print (int64 .Values.redis.port) | b64enc }}
  redis_password: {{ .Values.redis.password | b64enc }}
{{ else }}
  redis_host: {{ .Values.redis.externalConfig.host | b64enc }}
  redis_port: {{ print (int64 .Values.redis.externalConfig.port) | b64enc }}
  redis_password: {{ .Values.redis.externalConfig.password | b64enc }}
{{ end -}}
