apiVersion: v1
kind: Service
metadata:
  name: {{ include "kar.name" . }}-zookeeper
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: {{ include "kar.name" . }}-zookeeper
spec:
  type: ClusterIP
  clusterIP: None
  selector:
      {{- include "kar.selectorLabels" . | nindent 6 }}
      name: {{ include "kar.name" . }}-zookeeper
  ports:
  - name: zookeeper
    port: {{ .Values.zk.port }}
    targetPort: {{ .Values.zk.port }}
  - name: server
    port: {{ .Values.zk.serverPort }}
    targetPort: {{ .Values.zk.serverPort }}
  - name: leader-election
    port: {{ .Values.zk.leaderElectionPort }}
    targetPort: {{ .Values.zk.leaderElectionPort }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kar.name" . }}-zookeeper
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: {{ include "kar.name" . }}-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kar.selectorLabels" . | nindent 6 }}
      name: {{ include "kar.name" . }}-zookeeper
  serviceName: {{ include "kar.name" . }}-zookeeper
  template:
    metadata:
      labels:
        {{- include "kar.selectorLabels" . | nindent 8 }}
        name: {{ include "kar.name" . }}-zookeeper
    spec:
      containers:
      - image: {{ .Values.zk.imageRegistry }}/{{ .Values.zk.imageName }}:{{ .Values.zk.imageTag }}
        name: zk
        ports:
        - name: zookeeper
          containerPort: {{ .Values.zk.port }}
        - name: server
          containerPort: {{ .Values.zk.serverPort }}
        - name: leader-election
          containerPort: {{ .Values.zk.leaderElectionPort }}
