apiVersion: v1
kind: Pod
metadata:
  name: express-server
  annotations:
    kar.ibm.com/app: express
    kar.ibm.com/service: greeter
spec:
  containers:
  - name: server
    image: examples-js:dev
    env:
    - name: MAIN
      value: express/server.js
