apiVersion: batch/v1
kind: Job
metadata:
  name: stock-price-client
  labels:
    name: stock-price-client
spec:
  template:
    metadata:
      annotations:
        kar.ibm.com/app: stockPriceEvents
        kar.ibm.com/service: stock-client
    spec:
      restartPolicy: OnFailure
      containers:
      - name: stock-client
        image: us.icr.io/research/kar-dev/examples/js/stock-prices
        env:
        - name: MAIN
          value: stock-client.js
