#
# Copyright IBM Corporation 2020,2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: Service
metadata:
  name: kar-redis
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: kar-redis
spec:
  type: ClusterIP
  clusterIP: None
  selector:
      {{- include "kar.selectorLabels" . | nindent 6 }}
      name: kar-redis
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: kar-redis-0
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: kar-redis-0
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kar-redis-0
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
    nodePort: {{ .Values.global.redisNodePort }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kar-redis
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: kar-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kar.selectorLabels" . | nindent 6 }}
      name: kar-redis
  serviceName: kar-redis
  template:
    metadata:
      labels:
        {{- include "kar.selectorLabels" . | nindent 8 }}
        name: kar-redis
    spec:
{{- if .Values.global.persistence }}
      volumes:
        - name: kar-redis-pvc
          persistentVolumeClaim:
            claimName: kar-redis-pvc
{{- end }}
      containers:
      - name: redis
        image: {{ .Values.redis.imageRegistry }}/{{ .Values.redis.imageName }}:{{ .Values.redis.imageTag }}
        command: ["/bin/sh", "-c", "/usr/local/bin/docker-entrypoint.sh --requirepass $REDIS_PASSWORD"]
{{- if .Values.global.persistence }}
        volumeMounts:
        - mountPath: /data
          name: kar-redis-pvc
{{- end }}
        ports:
        - name: redis
          containerPort: {{ .Values.redis.port }}
        env:
        - name: REDIS_PASSWORD
          value: {{ .Values.redis.password }}

{{- if .Values.global.persistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kar-redis-pvc
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: kar-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}
