apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: source
  annotations:
    kar.ibm.com/integration: "true"
spec:
  flows:
  - from:
      uri: timer:tick
      parameters:
        period: "3000"
      steps:
      - to: http://financialmodelingprep.com/api/v3/quote-short/AAPL?apikey=demo
      - set-property:
          constant: mysource
          name: cloudevent.source
      - set-property:
          constant: quote
          name: cloudevent.type
      - process:
          ref: transformMessageToCloudEvent
      - to: kafka:InputStockEvent
      - log:
          message: ${body}
