apiVersion: apps/v1
kind: Deployment
metadata:
  name: incr-server
  labels:
    name: incr-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: incr-server
  template:
    metadata:
      labels:
        name: incr-server
      annotations:
        kar.ibm.com/app: myApp
        kar.ibm.com/service: myService
        kar.ibm.com/verbose: "info"
    spec:
      containers:
      - name: server
        image: us.icr.io/kar-dev/sample-incr:latest
        imagePullPolicy: Always
        env:
        - name: MAIN
          value: server.js
---
apiVersion: batch/v1
kind: Job
metadata:
  name: incr-client
  labels:
    name: incr-client
spec:
  template:
    metadata:
      annotations:
        kar.ibm.com/app: myApp
        kar.ibm.com/service: myClient
        kar.ibm.com/verbose: "info"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: client
        image: us.icr.io/kar-dev/sample-incr:latest
        imagePullPolicy: Always
        env:
        - name: MAIN
          value: client.js
