#
# Copyright IBM Corporation 2020,2023
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-agg
#  namespace: logging  
  labels:
    app: fluentd-agg
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-agg
#  namespace: logging  
  labels:
    app: fluentd-agg
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-agg
#  namespace: logging  
roleRef:
  kind: ClusterRole
  name: fluentd-agg
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd-agg
  namespace: logging  
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-agg
  namespace: logging
  labels:
    app: fluentd-agg
spec:
  selector:
    matchLabels:
      app: fluentd-agg
  template:
    metadata:
      labels:
        app: fluentd-agg
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: efk-type
                    operator: In
                    values:
                      - master

      serviceAccount: fluentd-agg
      serviceAccountName: fluentd-agg
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

      containers:
      - name: fluentd-agg
        image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch.logging.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENT_ELASTICSEARCH_USER
            value: "user"
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: "changeme"
#          - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
#            value: >
#              [
#                "/var/log/containers/fluentd-agg-*",
#                "/var/log/containers/svclb*",
#                "/var/log/containers/kibana*",		
#                "/var/log/containers/elasticsearch*"
#              ]
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
#          - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
#            value: /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc
#          subPath: aggregator.conf
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: fluentd-aggregator-conf
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers