#
# Copyright IBM Corporation 2020,2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: "3"
services:
  zookeeper:
    image: zookeeper:3.6
    hostname: zookeeper
    container_name: kar_zookeeper
    restart: "${RESTART_POLICY}"
    networks:
      - kar-bus
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    hostname: kafka
    container_name: kar_kafka
    restart: "${RESTART_POLICY}"
    networks:
      - kar-bus
    command: [start-kafka.sh]
    ports:
      - "31093:9093"
    environment:
      HOSTNAME_COMMAND: "hostname -f"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ONBUS:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: ONBUS://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: ONBUS://_{HOSTNAME_COMMAND}:9092,EXTERNAL://localhost:31093
      KAFKA_INTER_BROKER_LISTENER_NAME: ONBUS
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    depends_on:
      - "zookeeper"
  redis:
    image: redis:6.2
    hostname: redis
    container_name: kar_redis
    restart: "${RESTART_POLICY}"
    networks:
      - kar-bus
    command: ["/bin/sh", "-c", "/usr/local/bin/docker-entrypoint.sh --user karmesh allcommands allkeys on \\>act0rstate --port 6379"]
    ports:
      - "31379:6379"

networks:
  kar-bus:
    external: true
