version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: kar_zookeeper
    networks:
      - kar-bus
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    hostname: kafka
    container_name: kar_kafka
    networks:
      - kar-bus
    command: [start-kafka.sh]
    ports:
      - "31093:9093"
    environment:
      HOSTNAME_COMMAND: "hostname -f"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ONBUS:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: ONBUS://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: ONBUS://_{HOSTNAME_COMMAND}:9092,EXTERNAL://localhost:31093
      KAFKA_INTER_BROKER_LISTENER_NAME: ONBUS
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    depends_on:
      - "zookeeper"
  redis:
    image: redis:5.0
    hostname: redis
    container_name: kar_redis
    networks:
      - kar-bus
    command: ["/bin/sh", "-c", "/usr/local/bin/docker-entrypoint.sh --requirepass passw0rd --port 6379"]
    ports:
      - "31379:6379"

networks:
  kar-bus:
    external: true
