apiVersion: v1
kind: Service
metadata:
  name: kar-redis
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: kar-redis
spec:
  type: ClusterIP
  clusterIP: None
  selector:
      {{- include "kar.selectorLabels" . | nindent 6 }}
      name: kar-redis
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kar-redis
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: kar-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kar.selectorLabels" . | nindent 6 }}
      name: kar-redis
  serviceName: kar-redis
  template:
    metadata:
      labels:
        {{- include "kar.selectorLabels" . | nindent 8 }}
        name: kar-redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.imageRegistry }}/{{ .Values.redis.imageName }}:{{ .Values.redis.imageTag }}
        command: ["/bin/sh", "-c", "/usr/local/bin/docker-entrypoint.sh --requirepass $REDIS_PASSWORD"]
        ports:
        - name: redis
          containerPort: {{ .Values.redis.port }}
        env:
        - name: REDIS_PASSWORD
          value: {{ .Values.redis.password }}
