apiVersion: v1
kind: Pod
metadata:
  name: hello-server
  annotations:
    kar.ibm.com/app: helloWorld
    kar.ibm.com/service: greeter
spec:
  containers:
  - name: server
    image: examples-js:dev
    env:
    - name: MAIN
      value: helloWorld/server.js
