apiVersion: apps/v1
kind: Deployment
metadata:
  name: kar-injector
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: kar-injector
spec:
  replicas: {{ .Values.kar.injector.replicaCount }}
  selector:
    matchLabels:
      {{- include "kar.selectorLabels" . | nindent 6 }}
      name: kar-injector
  template:
    metadata:
      labels:
        {{- include "kar.labels" . | nindent 8 }}
        name: kar-injector
    spec:
      imagePullSecrets:
      - name: kar.ibm.com.image-pull
      containers:
      - name: injector
        image: {{ printf "%s:%s" .Values.kar.injector.imageName .Values.kar.injector.imageTag }}
        command: ["/kar/bin/kar-injector", "-tls_cert_file", "/var/run/secrets/kar.ibm.com/tls/tls.crt", "-tls_private_key_file", "/var/run/secrets/kar.ibm.com/tls/tls.key", "-port", "8443", "-sidecar_image", "{{ .Values.kar.injector.sidecarImageName }}", "-sidecar_image_tag", "{{ .Values.kar.injector.sidecarImageTag }}" ]
        ports:
        - containerPort: 8443
          name: webhook-api
        volumeMounts:
        - name: tls-certs
          mountPath: /var/run/secrets/kar.ibm.com/tls
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: kar.ibm.com.injector-tls
---
apiVersion: v1
kind: Service
metadata:
  name: kar-injector
spec:
  selector:
    {{- include "kar.selectorLabels" . | nindent 4 }}
    name: kar-injector
  ports:
    - port: 443
      targetPort: webhook-api
