#
# Copyright IBM Corporation 2020,2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kar-injector
  labels:
    {{- include "kar.labels" . | nindent 4 }}
    name: kar-injector
spec:
  replicas: {{ .Values.kar.injector.replicaCount }}
  selector:
    matchLabels:
      {{- include "kar.selectorLabels" . | nindent 6 }}
      name: kar-injector
  template:
    metadata:
      labels:
        {{- include "kar.labels" . | nindent 8 }}
        name: kar-injector
    spec:
{{- if .Values.global.affinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kar-type
                operator: In
                values:
                - system
{{- end }}
      imagePullSecrets:
      - name: kar.ibm.com.image-pull
      containers:
      - name: injector
        image: {{ printf "%s:%s" .Values.kar.injector.imageName .Values.kar.version }}
        command: ["/kar/bin/kar-injector", "-tls_cert_file", "/var/run/secrets/kar.ibm.com/tls/tls.crt", "-tls_private_key_file", "/var/run/secrets/kar.ibm.com/tls/tls.key", "-port", "8443", "-sidecar_image", "{{ .Values.kar.injector.sidecarImageName }}", "-sidecar_image_tag", "{{ .Values.kar.version }}" ]
        ports:
        - containerPort: 8443
          name: webhook-api
        volumeMounts:
        - name: tls-certs
          mountPath: /var/run/secrets/kar.ibm.com/tls
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: kar.ibm.com.injector-tls
---
apiVersion: v1
kind: Service
metadata:
  name: kar-injector
spec:
  selector:
    {{- include "kar.selectorLabels" . | nindent 4 }}
    name: kar-injector
  ports:
    - port: 443
      targetPort: webhook-api
